version: '3.8'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: Explorer
  #     POSTGRES_DB: ExplorerDb
  #   ports:
  #     - 5432:5432
      
  bitcoin-core:
    image: ruimarinho/bitcoin-core:0.17
    command:
      -printtoconsole
      -txindex=1
      -testnet=1
      -rest
      -rpcallowip=::/0
      -rpcport=18332
      --rpcuser=foo
      --rpcpassword="qDDZdeQ5vw9XXFeVnXT4PZ--tGN2xNjjR4nrtyszZx0="
      -server
    ports:
      - "18332:18332"
  
  bitcoincash-node:
    image: zquestz/bitcoin-cash-node
    command: 
    ports:
      - "18342:18342"