version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Explorer
      POSTGRES_DB: ExplorerDb
    ports:
      - 5432:5432
      
  bitcoin-core:
    image: ruimarinho/bitcoin-core:0.17
    command:
      -printtoconsole
      -txindex=1
      -rest
      -rpcallowip=::/0
      -rpcport=8332
      --rpcuser=foo
      --rpcpassword="qDDZdeQ5vw9XXFeVnXT4PZ--tGN2xNjjR4nrtyszZx0="
      -server
    ports:
      - "8332:8332"