// <auto-generated />
using Fontys.BlockExplorer.API.ForGeneration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fontys.BlockExplorer.API.Migrations
{
    [DbContext(typeof(BlockExplorerContext))]
    [Migration("20220623192556_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fontys.BlockExplorer.Domain.Models.Address", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.HasKey("Hash");

                    b.ToTable("Addresss");
                });
#pragma warning restore 612, 618
        }
    }
}
